### ISSUE TITLE
Guidelines on how to display FHIR Dosage (& Timing) in Belgium ?

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#110]
@jy95

Hello,

I heard that a couple of projects are going to use the FHIR Dosage (& Timing) ressource [Dosage - FHIR v4.0.1](https://hl7.org/fhir/R4/dosage.html)  : 
- UHMEP (referral prescriptions)
- FarmaFlux (delivered medications)
- Recip-e (medicinal prescriptions)
- VIDIS (which I work in)
- SAMv2 (a project is going to start in 2025 to turn medication posology into FHIR)
- … and many more I can list

In UK, they have clear specifications ( [Implementation guide for interoperable medicines](https://simplifier.net/guide/ukcoreimplementationguideformedicines/dosetotexttranslation?version=current) ) on how to display them.
Could we consider something like this in Belgium ? At least as guidelines ? (to ensure good communication between projects)

I created my own library on my free time with its documentation ( [GitHub - jy95/fhir-dosage-utils: Turn FHIR Dosage into human readable text in your wanted language and much more](https://github.com/jy95/fhir-dosage-utils) - [Hello from FHIR Dosage Utils | FHIR Dosage Utils](https://jy95.github.io/fhir-dosage-utils/)  ) because I was curious to have something complete to discuss.

Kind regards,

Jacques Y.

**Comment by jy95** [comment]
@bdc-ehealth Thanks Bart. A single comment, the title should be "Display guidelines for Dosage (& Timing)" instead, to match what is written here ;)

**Comment by bdc-ehealth** [comment]
WG: we do not think that the translations and display should be fixed in FHIR. The display is the responsibility of the client software, and the translation should be covered by a service that is similar to a terminology server.

**Comment by smals-jy** [comment]
In case it interests someone, I created a Java library for this concern : https://github.com/jy95/fds (and a demo spring boot app : https://github.com/jy95/spring-fhir-humanizer-api )

Many software will need at least complete FHIR belgian examples, hope it will be covered by https://ehealth.fgov.be/standards/fhir/medication/StructureDefinition-BeDosage.html in a near future
