### ISSUE TITLE
work on BeEncounter as from 26 June

### ISSUE THREAD

**Issue by KarlienHL7Belgium** [hl7-be/core#115]
11 Data Cap projects deal with this and profile has to be aligned among them - resulting from WG Patient Dossier Problem from 13 June

**Comment by bdc-ehealth** [comment]
A first attempt by Pablo Dalcantara: https://docs.google.com/document/d/1s0eO73DvutWIKOTElGglOf9B4phNlQDV/edit
other link: : https://docs.google.com/document/d/1s0eO73DvutWIKOTElGglOf9B4phNlQDV/edit?usp=sharing&ouid=114828987253817454981&rtpof=true&sd=true

**Comment by bdc-ehealth** [comment]
further handled in hl7-be/core-clinical#67
