### ISSUE TITLE
BeConsent: create build profile

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#130]
As requested by @annabel-uzl in https://be-ehealth-standards.atlassian.net/browse/ESI-790 . Please be aware that there is no project proposal known to the FHIR Validation Team that takes responsibility for this profile.

**Comment by bdc-ehealth** [comment]
@annabel-uzl : Please be aware that part of the functionality of this resource is already covered in https://www.ehealth.fgov.be/standards/fhir/patientwill/index.html

**Comment by costateixeira** [comment]
General note: when an issue is created based on a eHealth Jira ticket, we
should restart the (relevant) discussion or reproduce the focal part of the
issue in github, since eHealth Jira is not open for everyone.
