### ISSUE TITLE
NamingSystem for isurance company

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/core#22]
Hi all!
In the IG I see the NamingSystems [BeInsurancymembershipNamingSystem](https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem-be-insurancymembership.html) and [BeInsuranceNumberNamingSystem](https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem-be-insurancenumber.html), which is nice but I am looking for a NamingSystem to be used for identifying the healthcare insurance company. 

I believe in Belgium this happens based on a [3 digit identification code handed out by RIZIV](https://riziv.fgov.be/nl/professionals/andere-professionals/ziekenfonds/Paginas/contacteer-ziekenfondsen.aspx#.YpiQ9KhByUk). Does a NamingSystem for this already exists?

**Comment by bartdecu** [comment]
@ArdonToonstra Can you explain me the context in which you will use this?

**Comment by ArdonToonstra** [comment]
Hi @bartdecu , we are modeling the patient summary in FHIR based on the IPS / European patient summary / the Dutch 'BgZ'. These datasets contain insurance information about a patient. The information model for insurance information incorporates the 'European Health Insurance Card (EHIC)'. We are looking at how to represent the unique healthcare insurance company identification in FHIR. In the Netherlands, this is called UZOVI and contains 4 digits. Nictiz created the following NamingSystem for it: https://simplifier.net/nictizstu3-zib2017/d52c4a9e-1f3c-4924-926a-036fde004f0a The R4 profiles of Nictiz will contain a similar NamingSystem.

I think this is something you would want to define at least at the national level.

**Comment by bdc-ehealth** [comment]
I think you need this one: https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem-be-insurancenumber.html.

I looks a bit bizarre to me that you need the insurance number for research data...

**Comment by ArdonToonstra** [comment]
Thanks, @bdc-ehealth, I thought that the [BeInsuranceNumberNamingSystem](https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem-be-insurancenumber.html) was meant for the number under which the insured person is registered at the insurance company, not the identification of the insurance company itself.

**Comment by costateixeira** [comment]
This should be clarified in the specification - what is the NamingSystem supposed to identify.

**Comment by bdc-ehealth** [comment]
@costateixeira  I think this is an excellent moment to set up an HL7 workgroup for Insurance stuff. The MyCareNet project fits this group as well, and is still orphan.

**Comment by bdc-ehealth** [comment]
WG: @bdc-ehealth will write a proposal for a clearer description. The WG will approve afterwards.
