### ISSUE TITLE
BeOrganization (beLocation?) - campus number

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/core#24]
Organizations often have multiple locations; each location has its unique campus number (four digits) assigned by the government. How would the campus number best be represented using the BE core profiles?

**Comment by ArdonToonstra** [comment]
I believe this equals the HCOrganization.Site.SiteID (or site number) value as found in the [Common Base Registry for HealthCare Actor (CoBRHA)](https://www.ehealth.fgov.be/ehealthplatform/nl/service-cobrha-common-base-registry-for-healthcare-actor) Would this be appropriate to include in the BE core profiles?.

**Comment by bdc-ehealth** [comment]
related to #33

**Comment by bdc-ehealth** [comment]
solved in  #23
