### ISSUE TITLE
Invalid min cardinality of Human Language extension in BeAddress

### ISSUE THREAD

**Issue by ArdonToonstra** [hl7-be/core#31]
The [BeAddress profile](https://www.ehealth.fgov.be/standards/fhir/core/2.0.0/StructureDefinition-be-address.html) adds the human language extension ([http://hl7.org/fhir/StructureDefinition/language](http://hl7.org/fhir/R4/extension-language.html)) which has a cardinality of 1..1. 

The BeAddress profile relaxes the cardinality of the extension to 0..1 which is not valid. 

Goes wrong here: https://github.com/hl7-be/core/blob/7aa822b1d03356e399668f2650193c51bd28c067/input/fsh/profiles/BeAddress.fsh#L12

**Comment by bdc-ehealth** [comment]
Hi @ArdonToonstra 

I ran the address below through the validator (remark the missing language extension), and it caused no problems whatsoever.

```
    {
      "use": "work",
      "type": "both",
      "text": "120, Rue des Vulcans, 1000 Bruxelles",
      "line": [
        "120, Rue des Vulcans"
      ],
      "_line": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName",
              "valueString": "Rue des Vulcans"
            },
            {
              "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber",
              "valueString": "120"
            }
          ]
        }
      ],
      "city": "Bruxelles",
      "postalCode": "1000",
      "country": "BE"
    }
```
Validator result:

```
FHIR Validation tool Version 5.6.46 (Git# eca2fa5a5ce6). Built 2022-05-12T10:35:44.416Z (166 days old)
  Java:   1.8.0_281 from C:\Program Files\Java\jdk1.8.0_281\jre on amd64 (64bit). 3600MB available
  Paths:  Current = C:\Temp\empty\core, Package Cache = C:\Users\eh089\.fhir\packages
  Params: c:\Temp\empty\core\fsh-generated\resources\Organization-organization1.json -version 4.0.1
Loading
  Load FHIR v4.0 from hl7.fhir.r4.core#4.0.1 - 4572 resources (00:04.0534)
  Load hl7.terminology#4.0.0 - 4164 resources (00:01.0868)
  Terminology server http://tx.fhir.org - Version 2.0.14 (00:01.0952)
  Get set...  go (00:00.0094)
Validating
  Validate c:\Temp\empty\core\fsh-generated\resources\Organization-organization1.json   ..Detect format for c:\Temp\empty\core\fsh-generated\resources\Organization-organization1.json
  Load hl7.terminology.r4#3.1.0 - 4117 resources (00:05.0369)
  Load hl7.fhir.be.core#2.0.1 - 25 resources (00:00.0003)
 00:03.0606
Done. Times: Loading: 00:08.0642, validation: 00:08.0981. Memory = 1Gb

Success: 0 errors, 0 warnings, 1 notes
  Information: All OK
```

**Comment by bdc-ehealth** [comment]
@ArdonToonstra 

Maybe the confusion has to do with cardinalities on different levels:

1) the use of  the language within the extension which is mandatory 

Human Language |   | 1..1 | code
-- | -- | -- | --




2) the use of the extension itself, which may be optional. 


These are two different things.

**Comment by ArdonToonstra** [comment]
@bdc-ehealth, you are right, I incorrectly thought the extension became mandatory in the host profile too because Forge gave me an incorrect warning. Not sure how that came there. Is marks it as valid now.

Thanks!
