### ISSUE TITLE
RIZIV HciType code table

### ISSUE THREAD

**Issue by StevenDevooght** [hl7-be/core#32]
At ZORGI, we have a product (named Condor) that processes [RIZIV HealthCareWorkers & HealthCareInstitutions](https://webappsa.riziv-inami.fgov.be/DownloadCenter/nl). We would like to export the HealthCareInstitutions as HL7 FHIR.

As a base we use the `be-organisation` profile. As you can see in the sample message below we defined our own `condor-institutionCode`.

It would be nice if the [code table (HciTypes) described by the RIZIV](https://webappsa.riziv-inami.fgov.be/DownloadCenter/nl/Home/GetFile?fileName=SzvCodeTables.zip) would be part of this package. Especially because the messages will be processed by our customers (hospitals). Is this something that can be foreseen in the future?
```
{
  "resourceType": "Organization",
  "id": "hbafcfjh",
  "meta": {
    "profile": [
      "https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-organization"
    ]
  },
  "extension": [
    {
      "url": "http://zorgi.be/fhir/StructureDefinition/condor-institutionCode",
      "valueString": "710"
    }
  ],
  "identifier": [
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MD"
          }
        ],
        "text": "Medical License number"
      },
      "system": "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/nihdi",
      "value": "71052597"
    },
    {
      "use": "official",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "PRN"
          }
        ],
        "text": "Provider Number"
      },
      "system": "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/cbe",
      "value": ""
    }
  ],
  "active": true,
  "name": "AZ DAMIAAN",
  "address": [
    {
      "use": "work",
      "text": "GOUWELOZESTRAAT 100, 8400 OOSTENDE",
      "line": [
        "GOUWELOZESTRAAT 100"
      ],
      "_line": [
        {
          "extension": [
            {
              "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName",
              "valueString": "GOUWELOZESTRAAT"
            },
            {
              "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber",
              "valueString": "100"
            }
          ]
        }
      ],
      "city": "OOSTENDE",
      "postalCode": "8400",
      "country": "BE"
    }
  ]
}
```

**Comment by ArdonToonstra** [comment]
+1 for Sciensano. 
We are actually looking for the applicable codes for our 'OrganizationType' concept.  I believe these codes would eventually map to `Organization.type` in FHIR: @StevenDevooght no extension is needed if we have a code system uri for these codes.

The HciTypes contain a subset of codes you can see in the COBRHA viewer for type, as shown in the screenshot.  Could/should we get the complete list here?


![image](https://user-images.githubusercontent.com/20518398/208447110-c5a376c8-2d57-4dc3-96bd-1db573e43579.png)

**Comment by bdc-ehealth** [comment]
WG: discuss the meaning of this code with people from the COBRHA team and RIZIV/INAMI. @bdc-ehealth

**Comment by bdc-ehealth** [comment]
@StevenDevooght @ArdonToonstra : the activity codes that you can see in the (Flemish) COBRHA viewer are different from the HCIType. The activity codes are attributed by the same "authentic source" that created the HCO-number (#23 ) . HCIType is always attributed by the RIZIV/INAMI and is thus a Federal code. Because of its validity only in communications with RIZIV/INAMI, I propose to add the NamingSystem to https://github.com/hl7-be/nihdi-terminology
