### ISSUE TITLE
BePatient.gender should not be mandatory

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/core#38]
BePatient.gender is currently mandatory. 
When this was done, there was no issure tracking so we could not find the requirement behind this.
Since gender is personal information, per GDPR requirements, there should always be a reason on why this data element is required.

**Comment by bdc-ehealth** [comment]
WG: We need additional information about the possible values (FHIR has 4, KMEHR has 5, why?).

**Comment by bdc-ehealth** [comment]
WG: we agree that the gender is not mandatory. However, each specification is free to impose some constraints on the presence of the gender. We will describe this in the guidance of the core IG.

**Comment by bdc-ehealth** [comment]
@costateixeira 

Additional information about the gender, and about the logical model of the person (here patient) in general can be found here: https://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/bestand-rr/bestand-RR.pdf

On page 6/36, it contains the value that is not taken into account by FHIR (in Dutch it is: 004 Geslachtsverandering: litterally "change of sex")  

This is the additional value that is part of the KMEHR valueset.

**Comment by bdc-ehealth** [comment]
As the administrative gender in FHIR is a code and required, and thus cannot be replaced by another valueSet, I think that the international patient resource is a little 'over-profiled' here.

**Comment by costateixeira** [comment]
This issue was about gender being mandatory, so I guess it can be closed if
that's the agreement.

For valuesets, the only issue was the early decision, but there's no point
there besides clarifying what was / should be meant: whether the implicit
decision was that in Belgium, on FHIR, only those 4 values should be
supported, or whether this was overlooked and BePatient should have 5
values.
Once the logical model captures what is needed, the technical decisions
will follow.

**Comment by bdc-ehealth** [comment]
solved in #37
