### ISSUE TITLE
BeOrganization has a slice for NISS number - is that needed?

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/core#39]
Why does BeOrganization have a slice for NISS?
We don't think that an organization should be identified with a NISS, and if the NISS is supposed to identify a person or people, this would be through BePractitioner, BePractitionerRole,..., not Organization.

**Comment by bdc-ehealth** [comment]
WG: at the moment, we don't see any use cases for this. If there is a current use, it will be based on a package before this change, so it will not impact the use if we remove it. A use case that needs it, can introduce it again.
