### ISSUE TITLE
Add BeCodedAnnotation for referral prescription

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#52]
The referral WG asks the addition of codeable annotations https://github.com/hl7-be/referral/issues/237

**Comment by bdc-ehealth** [comment]
Preapplied for WG referral

**Comment by bdc-ehealth** [comment]
WG: we agree on this, if the context of the extension is changed to Annotation.

**Comment by costateixeira** [comment]
there is a standard extension for adding a type (codeable concept) to Annotation:
https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-annotationType.html
If the intent is the same (seems so), we should use that one, not a custom extension

**Comment by costateixeira** [comment]
(Confirming that we agreed on the concept, but we held on the implementation of a custom extension if there would be a standard extension, which seems to be the case)

**Comment by bdc-ehealth** [comment]
@costateixeira ,

We cannot use https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-annotationType.html , since it has not been officially released as of today 13/02/2024. 

https://hl7.org/fhir/extensions/extension-registry.html is the latest release of the extension package (2023-03-26), and it does not contain http://hl7.org/fhir/StructureDefinition/annotationType .

We will have to stick with our own version for the time being.
