### ISSUE TITLE
Format description of SSIN

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#54]
I was not able to find a description of the format of the SSIN (some people use dots or dashes to format the SINN number into its composing parts).

All examples at hand use the formatting without dots or dashes. This seems to have been the approach in KMEHR as well. 

Does the WG agree with using the format without dashes and/or dots?

**Comment by nicovn** [comment]
Same remark for the other identifiers, e.g. RIZIV number of a hospital in the Organization resource

"system" : "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/nihdi",
"value" : "71030031"

Is "71030031" a valid value for the hospital RIZIV/NIHII number or should we use 11 digits ? or another format ...

I think that clarification is required to avoid issues when people start implementing the BE Core profiles ...

**Comment by bdc-ehealth** [comment]
Brian Thieren agrees with @nicovn 

WG: we agree for NISS,  for company indentifications,  we check the format of the belgian CBE, but not the format of foreign company identifications.

**Comment by bdc-ehealth** [comment]
Open question: for a general NIHDI number, there is no explicit mentioning of the length. Some parties use 8, some 11 digits. What do we do with this?

**Comment by bdc-ehealth** [comment]
@annenerenhausen

Answer from RIZIV/INAMI

[2:41 PM] Bart Decuypere (EHEALTH)
Anne, les numéros INAMI, on préfère la version 11 chiffres ou la version 8 chiffres, ou les deux?
[3:01 PM] Anne Nerenhausen (RIZIV-INAMI)
Bonjour Bart.
[3:02 PM] Anne Nerenhausen (RIZIV-INAMI)
Bonne question, je vais quand même me renseigner avant de te répondre. D'accord ?
[3:20 PM] Bart Decuypere (EHEALTH)
Tu me fais un retour quand?
[3:52 PM] Anne Nerenhausen (RIZIV-INAMI)
j'ai envoyé la question. J'attend la réponse.
[4:08 PM] Anne Nerenhausen (RIZIV-INAMI)
Bart. C'est dans quel contexte ?
[4:08 PM] Anne Nerenhausen (RIZIV-INAMI)
les Care Sets ?
[4:09 PM] Bart Decuypere (EHEALTH)
Le contexte des standards. Si on indique qu'un identifiant est du type NIHDI, qu'est-ce qu'on peut attendre en tant que logiciel?
[4:16 PM] Anne Nerenhausen (RIZIV-INAMI)
les 3 dernières positions sont pour les compétences. Mais j'ai renvoyé la question à Yves pour être sûre de la réponse. Dès qu'il me répond, je te contacte.
[4:27 PM] Anne Nerenhausen (RIZIV-INAMI)
réponse de Yves : Les 3 dernières positions donnent juste la qualification, à mon sens juste nécessaire pour les cas plus sensibles, et donc cela sera utile d'avoir les 11
[4:28 PM] Bart Decuypere (EHEALTH)
OK, alors, c'est 11.
[4:28 PM] Anne Nerenhausen (RIZIV-INAMI)
oui

**Comment by bdc-ehealth** [comment]
WG: the workgroup agrees, this can be merged into the master branch.
