### ISSUE TITLE
Use legal description for medical specialities

### ISSUE THREAD

**Issue by Standards1** [hl7-be/core#56]
In the FHIR Value Set https://ehealth.fgov.be/standards/fhir/core/CodeSystem-cd-hcparty.html another description is used for the medical speciality than the one defined in the KB 25 november 1991 houdende de lijst van bijzondere beroepstitels voorbehouden aan de beoefenaars van de geneeskunde, met inbegrip van de tandheelkunde. Hospitals developing a SNOMED CT RefSet for pneumology and want to align to the eHealth Value Set dont feel that "pulmonology" and "pulmonologie" is the right term to use. The Dutch translation used in the KB, f. ex. is "pneumologie". They also ask to review all the values in the Value Set in accordance with the KB.

**Comment by bdc-ehealth** [comment]
@Standards1 

We will gladly modify any suggestion to the translations of this valueset, but we must stress that we are not a translation agency. The values we have in this valueset ( I stress the values, not the translations) originate from COBRHA, and not immediately from the law. To my knowledge, the translations used here are not normative, only the values of the codes. 

Therefore, if there are any other translations that should be changed besides the "pneumology" example, we would like to receive a list with the valid translations. 

Furthermore, from information by RIZIV/INAMI, this valueset should be replaced in the future with a list of SNOMED CT codes, which is not yet available at the moment.

**Comment by Standards1** [comment]
Thank you for your reply and the modification of the term. It is incumbent on the owner of the list of translations to check it.
The need for a list of SNOMED CT codes has been communicated to the terminology centre.

**Comment by bdc-ehealth** [comment]
This remark (with regard to pulmonologie) has already been adressed in change: https://github.com/hl7-be/core/commit/b485e99182a34c0681c202314ba088e32e935b4a
