### ISSUE TITLE
Set up BeCommunication and/or BeDocumentReference

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#60]
Proposal by @MCauchet
[HL7 BE WG Infra Scty FHIR 20230921_FUAN_Attachments_Smals_agenda_item.docx](https://github.com/hl7-be/core/files/13030248/HL7.BE.WG.Infra.Scty.FHIR.20230921_FUAN_Attachments_Smals_agenda_item.docx)

Additional comments by @ftavernier
As mentioned in the meeting, we are working for several years on the MHD profile from IHE : https://profiles.ihe.net/ITI/MHD/. In our Brusafe+ implementation, there is a mapping from KMEHR to XDS and we worked on the MHD profile to also include a REST API in our XDS environment. 
We aren’t sure that is the way to go for exchanging documents in the future and we don’t want to force this IHE profile on other but we would like to participate in the discussions due to our experience with it.
 
Also, I really think that all the hubs should participate in a discussion where standardization of exchanges of documents from external source are discussed. We should make it clear that this is also under discussion if we standardize BeDocumentReference (or I am wrong and it’s outside of the scope of this discussion).

**Comment by bdc-ehealth** [comment]
@PBACIN

Juste pour te dire que nous sommes aussi intéressés par le profile que tu ferais sur la ressource DocumentReference.

Nous devons échanger des documents pdf entre les hôpitaux et les oas.
Nous pensions utiliser la ressource DocumentReference.

**Comment by bdc-ehealth** [comment]
@Mcauchet

From: Maxime Caucheteur (SMALS) <***@***> 
Sent: 06 November 2023 09:01
To: Bart Decuypere (eHealth) <***@***>
Cc: Brecht Van Vooren (SMALS) <***@***>
Subject: Vitalink - DocumentReference profile   

Hi Bart, 

Following our discussions about a DocumentReference profile for Vitalink for Attachments, I would like to give you some feedback on required/must support fields for us. 

Required/Supported fields 

 Required 

subject: type BePatient
 

 Must support 

author

context.related

**Comment by bdc-ehealth** [comment]
@PBACIN, @Mcauchet, @ftavernier,

I provided a first attempt to profile these resources based on your input. 
https://build.fhir.org/ig/hl7-be/core/branches/issue-60/StructureDefinition-be-communication.html
https://build.fhir.org/ig/hl7-be/core/branches/issue-60/StructureDefinition-be-documentreference.html

We also need to make a "Logical Model" for these resources.  Can you provide some suggestions?

**Comment by PBACIN** [comment]
Bonjour Bart,

Philip Sidgwick va en principe suivre ce sujet.

Mais je vois déjà que dans le profile https://build.fhir.org/ig/hl7-be/core/branches/issue-60/StructureDefinition-be-documentreference.html, pour l'author, il faut mettre les Be...
[cid:6f2e675e-5e34-4d2f-a6d3-27bf89ae5cb9]

--
Bien à vous,
Met vriendelijke groeten,
Kind regards,
[https://ci4.googleusercontent.com/proxy/FydO-s3iQwuRbD6iaUD4j5QAY1FnvMLfz1HSg6PTvCKSQKo_dy9i3uRSrq3ZrtRx7XXCBgKSuqSDSqNK89KC_xbjT8LtYeEBCm0Y1OpxtgeEwDg=s0-d-e1-ft#https://drive.google.com/uc?id=1bOy2c1OKd6kf8w1U_Hy0J_9SrDPUtNnU]
Philippe Baise

Architect

Cellule de coordination du CIN - NIC Coördinatiecel

[https://ci6.googleusercontent.com/proxy/Xq3hntJEq2rjJzR0uWCVm3clsSla7NsI7xyRuy0B6esGxKEs0TJKSCBJd0PTJnw80_-gOm3yRwJoGtSWipm4TqjnmSCEllHm6WPq2oze68mmA8DO6Mj2dGBHroByKflVGCBL0c-wyQ3vCF92=s0-d-e1-ft#https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
+3228917252
[https://ci5.googleusercontent.com/proxy/u9Dqq8IRTYcA9pxGhij8X1100IBTEBNk6GfgLex2wy5mIUGt4EvtpI__1csTElV-MUMrqJCa2SjWZkRDmYNbTv260GIk6RQb8BWD6Fub4s38olgLolJ-Y0ZMzSkDaCxhCmOgByGso4GxlMz7=s0-d-e1-ft#https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
***@***.******@***.***>
[https://ci5.googleusercontent.com/proxy/bDGbdhNSZAZaKWHjXdHMW3DL3PklwLU9F5lSquHVukVuOVNDm_0LSPw8ckOtJwduaqdVOyJnATN5reUqPaX3QjUNCZkwbG2Ac8UdOzrywgI_nREPLk66UFxOhX3uiKMJOqLfWEBJyXQ51Tk=s0-d-e1-ft#https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.cin-nic.be<https://www.cin-nic.be/>
[https://ci5.googleusercontent.com/proxy/PMsX6QYblfid2-Aq_atF0w8D-5O2KEMGfclrImAJEOsQqE_sbKhMfAd7gH3akRnGu3ErEwVfaOuRfuDxpUBCSL-LKhPfwPnP1FnJHgaOjcrmV2CgMlczkQKYJb-bo0qnAEo7PcQNq51IElkIZFk=s0-d-e1-ft#https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
Manhattan Center /7ème étage Avenue du Boulevard 21, Boîte 7, 1210 ***@***.***,4.3547581,17z/data=!4m9!1m2!2m1!1sManhattan+Center+%2F7%C3%A8me+%C3%A9tage+Avenue+du+Boulevard+21,+Bo%C3%AEte+7,+1210+Saint-Josse-ten-Noode!3m5!1s0x0:0x627cc2819bce6c1a!8m2!3d50.85605!4d4.3567369!15sCltNYW5oYXR0YW4gQ2VudGVyIC83w6htZSDDqXRhZ2UgQXZlbnVlIGR1IEJvdWxldmFyZCAyMSwgQm_DrnRlIDcsIDEyMTAgU2FpbnQtSm9zc2UtdGVuLU5vb2RlkgEab2ZmaWNlX3NwYWNlX3JlbnRhbF9hZ2VuY3k>
Manhattan Center /7de verdieping Bolwerklaan 21, Bus 7, 1210 Sint Joost Ten ***@***.***,4.3547581,17z/data=!4m9!1m2!2m1!1sManhattan+Center+%2F7%C3%A8me+%C3%A9tage+Avenue+du+Boulevard+21,+Bo%C3%AEte+7,+1210+Saint-Josse-ten-Noode!3m5!1s0x0:0x627cc2819bce6c1a!8m2!3d50.85605!4d4.3567369!15sCltNYW5oYXR0YW4gQ2VudGVyIC83w6htZSDDqXRhZ2UgQXZlbnVlIGR1IEJvdWxldmFyZCAyMSwgQm_DrnRlIDcsIDEyMTAgU2FpbnQtSm9zc2UtdGVuLU5vb2RlkgEab2ZmaWNlX3NwYWNlX3JlbnRhbF9hZ2VuY3k>



[https://ci6.googleusercontent.com/proxy/vCIQEUlz4rXYBu9p4I4TuuJJYS0eNL7YlWL3sCArsXBSuDtk06uKKIg3n6KwrLQqWGK-I_IePvyzbFQzgEGo2A-oBxIdLEwE8dQr2BOP88oMxXQ=s0-d-e1-ft#https://drive.google.com/uc?id=1mU9TkctCMwbBxZuhL7M_-jTiYVq3CHT3]<https://www.youtube.com/mycarenet>
________________________________

**Comment by costateixeira** [comment]
The logical models should always come first, the profiles later. We had in the past a first iteration on BeCommunication (models and profiles) which was abandoned. 
We need to start this from those models. I will resurface those models before we embark on profiling.

**Comment by bdc-ehealth** [comment]
@costateixeira ,

Could you please share your input with the group?

**Comment by costateixeira** [comment]
The model was taken by eHealth at the time for publication. Not sure what
happened with it.
I can resurface that, should not be a difficult thing to profile.
The key point is to improve on previous work, not to start another profile
from scratch or without the data requirements.

**Comment by bdc-ehealth** [comment]
@Philip-Sidgwick

Thanks for making an account.

**Comment by bdc-ehealth** [comment]
Werner De Mulder would like to add facilityType: (kind of institution). WG: decides that this is already covered by context.related.

**Comment by bdc-ehealth** [comment]
WG: we decide to call the logical model: BeModelPatientDocument. Since this no longer overlaps with BeCommunication, there is no issue anymore.

**Comment by bdc-ehealth** [comment]
Philip Sidgwick: 
patient
riziv hospital/riziv practitioner as author
category - diabetes - level - targetgroup/type
document: attachment/pdf

open point: signatures / attester

**Comment by bdc-ehealth** [comment]
WG: we expect a mime-type to be present. We allow all mimetypes, even custom ones.

**Comment by bdc-ehealth** [comment]
WG: we approve the logical model in branch issue-60. It can be merged with the main branch.
