### ISSUE TITLE
Correct issues in qa.html as asked during validation team

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#87]
https://wiki.hl7belgium.org/index.php?title=Minutes_-_FHIR_Validation_Group_2024-03-28#:~:text=Issues%20in%20QA%20must%20be%20managed%20in%20an%20ad%2Dhoc%20meeting%20with%20Jose%20and%20Bart

**Comment by bdc-ehealth** [comment]
@costateixeira Could you propose some way of working to illustrate references to 
1) another server
2) a particular version of a resource (using the ``history`` bit in the url)

**Comment by bdc-ehealth** [comment]
@costateixeira 
I still see some errors in the qa.html: https://build.fhir.org/ig/hl7-be/core/branches/fixes/qa.html . Can I already merge this to the releasecandidate branch?

![image](https://github.com/hl7-be/core/assets/90335317/6bf77851-a64b-431d-b2fc-3950d1c38df9)
![image](https://github.com/hl7-be/core/assets/90335317/09a7fb05-2a08-47a1-94f1-2238892164fb)

**Comment by costateixeira** [comment]
not yet, this needs some decisions first.

**Comment by costateixeira** [comment]
For planning purposes : the solution for this may be changing the example content, not the tooling.

**Comment by costateixeira** [comment]
Both fixes are available, pending a decision to a) ignore, b) workaround, remove source of issues (unsupported examples).
The workaround is a new feature that adds complexity and will still present a QA error.

**Comment by bdc-ehealth** [comment]
see #102 and #103
