### ISSUE TITLE
Nationality/double nationality

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/core#89]
WG: we think the indication of nationality and double nationality is important. However we do not know yet if we want to use two fields or a * cardinality for nationality. 

@costateixeira will provide some examples on how to solve this.

**Comment by costateixeira** [comment]
there is a standard extension for citizenship
https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-patient-citizenship.html

if we really want to talk about "nationality" (as in country of birth?)  we have another standard extension

**Comment by bdc-ehealth** [comment]
addressed in f6df746270c927dfcbbd88a46ea92070ce515292
