### ISSUE TITLE
Sushi problem with html in new release?

### ISSUE THREAD

**Issue by annabel-uzl** [hl7-be/core#93]
I notice some small html issues, probably sushi related but better save than sorry

See screenshots: first is in the menu balk (white space), other one is one the artifacts page - hyperlink (I think wrong accents? ´ vs ' ?)
![image](https://github.com/hl7-be/core/assets/91048958/2b8f8a7b-b331-4298-9b40-1b3d2563e042)
![image](https://github.com/hl7-be/core/assets/91048958/cd4854be-c4d6-4e9f-8eda-e294284cc4f0)

**Comment by costateixeira** [comment]
both are editorial issues. The first one is due to broken links, the second is the formatting is not correct.
