### ISSUE TITLE
BeOrganization identifier

### ISSUE THREAD

**Issue by HanneVuegen** [hl7-be/core#99]
HCO number is missing as a possible identifier for organizations. Can this be added?

**Comment by bdc-ehealth** [comment]
@HanneVuegen ,

you can add the HCO-number to the identifier field. See this information: https://www.ehealth.fgov.be/standards/fhir/core/StructureDefinition-be-organization-definitions.html#Organization.identifier . It is not necessary to add it explicitly, as, as far as I am aware, an HCO-number is only used in Flanders.

**Comment by bdc-ehealth** [comment]
See #23 for more explanations on the HCO-number.
